---
- name: Install kibana plugins
  command: "./bin/kibana-plugin install {{ item }}"
  args:
    chdir: "/usr/share/kibana"
  with_items: "{{ kibana_plugins }}"
  when: kibana_plugins != ""
  register: result
  failed_when: ( result.rc not in [ 0, 70 ] )
...
